# Generated by Django 5.2.4 on 2025-07-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
